name:                llvm-hs-sample-compiler
version:             0.1.0.0
github:              "githubuser/llvm-hs-sample-compiler"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2022 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/llvm-hs-sample-compiler#readme>

dependencies:
- base >= 4.7 && < 5
- parsec
- llvm-hs == 9.0.1
- llvm-hs-pure == 9.0.0

library:
  source-dirs: src

executables:
  llvm-hs-sample-compiler-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - llvm-hs-sample-compiler

tests:
  llvm-hs-sample-compiler-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - llvm-hs-sample-compiler
